### PR TITLE
Breaking configure def into providers. Cleaning syntax

### PR DESCRIPTION
**Pull request by SamuelDavis**

### CODE REVIEW

**Comment by sudo-reboot** [comment]
for my own edification, where does all that `new_resource` stuff come from? i don't see it defined outside of the providers

**Comment by SamuelDavis** [comment]
The new_resource is the instance of the resource created when you call it in a recipe. That resource instance is then passed to the provider (which must have the same name) so it can have a handle on any arguments you've defined and want to pass to the provider.

**Comment by sudo-reboot** [comment]
oh ok, so `new_resource` is just an object that wraps all the parameters, i see it now, thats not super clear. but i'm not good at ruby or chef so theres that

**Comment by SamuelDavis** [comment]
The way I thought about it was, to create a PHP context, the resource is like the function declaration and constructor. The provider is the body of the method and new_resource == $this.

I think it's astoundingly unclear and unpleasantly redundant but this is apparently the *done* thing

**Comment by sudo-reboot** [comment]
`done`?

**Comment by SamuelDavis** [comment]
I think I'm done.

**Pull request merged**
